### ISSUE TITLE
Strange copy in Who to Notify widget

### ISSUE THREAD

**Issue by markoa** [operately/operately#1307]
Here's an example:
<img width="329" alt="Screenshot 2024-10-10 at 15 49 07" src="https://github.com/user-attachments/assets/f76b8248-e1cf-4458-8ddf-3ac5363a67e9">

> Only the following person I selected

I probably haven't noticed at an earlier stage, but I think that this wrong. Should be _Only the following people I select_.

I guess the reason is says 'person' is because of the non-changeable inclusion of the reviewer.

**Comment by Rockyy174** [comment]
Assuming this is not a bug, I'm afraid this is the expected behavior. 

I will try to explain how the widget works:

The reason why it shows "person" instead of "people" is because only one person is selected. But you don't see the person's avatar because "All 29 people ..." is the current option.

The reason why only one person is selected (even if you just loaded the page) is because, for goals and projects, champions and reviewers are always selected. However, the current logged-in person is not included in the list. Therefore, if either a reviewer or champion try to check in a project or goal, the default text will be "Only the following person I selected".

If you click on "Only the following person I selected", the people selection pop-up will appear. If you click on "Never mind", the pop-up will close and you will see the person's avatar. When you see the avatar, the text makes more sense. 
If you click on it again and select someone else, the text should change to "people".

This behavior can be changed, of course. So, when "Only the following person I selected" is NOT the current option, the avatars don't appear and the text is always "people". 

But in that case, if "Only the following people I selected" IS the current option and only one person is selected, should the text still be "people"? Or should it be "person" then?

Assuming the latter is true, in a practical example, if the text should be "person" when only one person is selected, what happens if the user switches between the options without changing the people selection? Will the text keep switching between "person" and "people" even though the selection is not changing?


I'm aware that my explanation may not be completely clear. Just let me know if something got too confusing.

**Comment by markoa** [comment]
I'd pin it down to the past tense _selected_ that made me feel uneasy, like whoah I haven't done anything what are you on about?

My proposal is for the label to be static "Only the people I select" , so don't change based on input. When that option is selected, the label + avatar(s) make the situation crystal clear.

**Comment by Rockyy174** [comment]
Got it!
