### ISSUE TITLE
Dead review item

### ISSUE THREAD

**Issue by markoa** [operately/operately#818]
I have an old one where when I click to open I get an error:

<img width="397" alt="Screenshot 2024-08-01 at 12 01 33" src="https://github.com/user-attachments/assets/4d4b61c2-4e8d-4db6-a1fd-daf58204cf82">

`goal-updates/2024-01-26-FaIliaZlkfzcRwsohji5zA`

**Comment by shiroyasha** [comment]
Leaving this here as it might be similar to the one I got: https://github.com/operately/operately/issues/792.

**Comment by Rockyy174** [comment]
It seems the problem is that, for this specific goal update, the `get_goal_progress_update` query is returning the result with `goal_target_updates` as `null`:

![tmp-1](https://github.com/user-attachments/assets/83959df1-4ec1-4dc2-83bb-19def683b196)

It should return something like this:

![tmp-2](https://github.com/user-attachments/assets/10c81f25-56df-4348-a293-9495c284e835)

I took a look at our serializer and it turns out that `goal_target_updates` is populated with the data in `update.content["targets"]` which must itself not exist. Here is the code in the serializer:

```
goal_target_updates: update.content["targets"] && Enum.map(update.content["targets"], fn t ->
        %{
          id: t["id"],
          name: t["name"],
          from: t["from"],
          to: t["to"],
          value: t["value"],
          unit: t["unit"],
          previous_value: t["previous_value"],
          index: t["index"],
        }
      end)
```

My guess is that, since this update is very old, the data must have been different back then.

I can think of a few ways to solve this issue:

- Add an extra condition to the query so that such updates are not returned by the `get_assignments` query
- Add a data migration to populate `update.content["targets"]`
- Update the front end, so that it doesn't break when `goal_target_updates` is `null`

What do you think, @markoa and @shiroyasha?

**Comment by shiroyasha** [comment]
> If my guess is correct and the data used to be different, my favorite approach would be to fix it with a data migration. Then, we wouldn't change the code to handle data that isn't even generated anymore.

I agree 👍 Otherwise, the code will contain additional conditionals about cases which are no longer possible and remain a consistent "why do we even need this" in the codebase.

**Comment by shiroyasha** [comment]
I've executed the data migration from the above migration. cc @Rockyy174 @markoa 

@markoa please tell us if the dead item was resolved.

**Comment by markoa** [comment]
I was able to open and ack it.
